language: c

addons:
    apt:
        packages:
            - lib32stdc++6

env:
    global:
        - secure: dgclZCb3Q72j88VycYHuLKyla7XHQe/U5SM0zdSjBjZkZe+mIvIgsVSYLvmX/N8ATXfLDBvmUdL7C1rMoXCJzH+3tlVNzwog82EMi03+BwVhmVtItAu3QAEucbwFHZeY6nkj/IlqP9p+k7Bm4AsFzeSuV2mWyyK4IgykdEs1MYAjNNgI0aXEBWxGT/u4IUb4Cv6CuHBgomoC0sNDuE64HV4Src15Lg3prSPVUmdtu0XtWNTTy6i5mC/zzpE2ELJlZXqSWZlOdueMUgnf01gUF2fh64GmSYobth2ItDpPDWZeWps4csXINyVvgkGGYn1IWuEyH9HEpp233rI1GG/BYw4SrJmWjtP6K6dlCLTx4By0t2rS6mWHEIK1G8Tb161E1Jr7GupfD5aeieZKJdtxl9PQK5fsuiRVoEsHUxthtlyEIy6j2cjrubrMd1RxvOgUY8AOC6ZgWJEEr0lafnGxytKiEZIX5q+74/S4k9WXZ35yV1Womtf2IrtmbLLPcmxU6AO662OgOiuQalNjEbUiSe9vZZ3WNn3AgQcVkFuEVy4Jeord9ez0rhKRPmwf1OUcaA/NqEWOUDRCgPYrcfGf0jcS42b6qKHjZTwlm8T/cM1dqFEv3kEJZ3a7HW5nYXU8IYyb7b6vPiOLHZJALLu/HC61PAiHJQXIDjo0TQh8tQM=
    jobs:
        - SOURCEMOD=1.10
        - SOURCEMOD=1.11

before_script:
    - mkdir build && cd build
    - wget "https://www.sourcemod.net/latest.php?os=linux&version=$SOURCEMOD" -O - | tar -xz addons/sourcemod/scripting
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - cp -R $TRAVIS_BUILD_DIR/addons/sourcemod/scripting/* .

script: ./compile.sh advertisements.sp

before_deploy:
    - mv compiled/* $TRAVIS_BUILD_DIR/addons/sourcemod/plugins/
    - cd $TRAVIS_BUILD_DIR
    - tar -czf release.tar.gz addons/
    - sed -e "s/\$TRAVIS_TAG/$TRAVIS_TAG/" update.txt.template > update.txt
    - git config user.name "Travis CI"
    - git config user.email "travis@example.com"
    - git remote set-url origin https://ErikMinekus:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    - git checkout --orphan gh-pages
    - git rm -rf .
    - git add addons/ update.txt
    - git commit -m "Deploy to GitHub Pages"
    - git push --force --quiet origin gh-pages > /dev/null 2>&1

deploy:
    provider: releases
    api_key:
        secure: l298wqXu+PkzKVKLDL+OSS/Uie4wbtcW9bNmqo1G7c38Yr1gdJoztYM0N1yXZxWdsHGjZi1gQ6GnS8kEmp6duDp8Q7Ou8TWBYhzHM7Ye0XFsHhISBtBpSunVbqMxD1yJDuT9Rg0f8+TgiSXGY86E3x2F8lHoFXjFiVNv8dWd0cDDzXGE43bFhDtle0Rm9tXJfRe1E7yPIMe6epbUZpUL5Dp244b7xirjfxOhFseirwVy+cmCZVehOoUKuIpVuKoKijAJzP/v1g79y3ZtaRKVn+1bV0seqOBcwmWSy5QlmwomSpxNsbERJ0dc7TTTw5W5ldzCK2bHOTEFQyE4dJ1OSuw4J9Tx3i/Dfp4UDpPif0ME7i/wOmy5X6uwc3puou51AemTqDmnbI6ROvKzep3AofsDklrtqQxJ6fscsJpy92lD9Ql/eVOy+wphwYAR5T+YsDfNOk0EpFeolIwAs4iky/e1nL9aAp+DdjacGTRpJPfmZc/etXAvLhaJ1yy49NwPmm28YDQf2AARk2WpDDI+Kw2tdqKDcviRlGId5Tn0jEB13xtDqEplTuye078L+Rqumcq7a4744x1oudZ+62sEJ1pc2Z2i3v6Fr160oWl/FJ0jOxt302Kk8v5or94nFr3/xka+Tq51knXL85A3DLZ/P385fIk28t47/1mp7wFPysI=
    file: release.tar.gz
    skip_cleanup: true
    on:
        tags: true
        condition: $SOURCEMOD = 1.10
